name: logger-plugin-kt-ci

on:
  pull_request:
    paths:
      - "logger/implementations/kt/**"

jobs:
  ci:
    name: logger-plugin-kt-ci
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test
        run: ./gradlew build
        working-directory: ./logger/implementations/kt