name: logger-plugin-kt-cd

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "logger/implementations/kt/**"

jobs:
  cd:
    name: logger-plugin-kt-cd
    if: |
      github.event.pull_request.merged &&
      startsWith(github.event.pull_request.title, '[CD]') != true &&
      github.event.pull_request.user.login != 'github-actions'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test
        run: ./gradlew build
        working-directory: ./logger/implementations/kt

      - name: Publish
        run: ./gradlew publish
        working-directory: ./logger/implementations/kt
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}